server:
  port: 9090
spring:
  application:
    name: auth-center
  datasource:
    url: jdbc:mysql://localhost:3306/auth-center?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: yibo
      # mysql 6.x以上 com.mysql.cj.jdbc.Driver
      # mysql 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true